name: Deploy Snippets

on:
  push:
    branches:
      - 'main'
    paths:
      - 'snippets/**'

jobs:
  deploy_snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

